version: '2'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/home/docker/rethink_ws
    ports:
      - "3000:3000"
    environment:
      RDB_HOST: rethinkdb
      RDB_URL: rethinkdb://rethinkdb:28015/rethinkws
    depends_on:
      - rethinkdb
  rethinkdb:
      image: rethinkdb:2.3
      ports:
        - "8080:8080"
