version: '2'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/home/docker/rethink_ws
    ports:
      - "3000:3000"
    environment:
      RDB_HOST: rethinkdb
      RDB_URL: rethinkdb://rethinkdb:28015/rethinkws
    depends_on:
      - rethinkdb
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rethinkws_development
      MYSQL_USER: rethinkws
      MYSQL_PASSWORD: rethinkws
    volumes:
      - ~/dockerdata/rethink_ws/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  rethinkdb:
      image: rethinkdb:2.3
      ports:
        - "8080:8080"
